apiVersion: v1
data:
  mapRoles: |
    - groups:
    - system:masters
    rolearn: arn:aws:iam::357232275748:role/UdacityFlaskDeployCBKubectlRole
    username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::357232275748:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QASVS9LJSVQ4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-22T15:42:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-22T15:42:37Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-03-25T17:11:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "737615"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dea97d75-9945-49af-91d6-8cac3e66659c
